/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSystemsRouteImport } from './routes/_authenticated.systems'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated.people'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated.access'
import { Route as AuthenticatedSystemsIndexRouteImport } from './routes/_authenticated.systems.index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated.people.index'
import { Route as AuthenticatedSystemsSystemIdRouteImport } from './routes/_authenticated.systems.$systemId'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated.people.$personId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemsRoute = AuthenticatedSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemsIndexRoute =
  AuthenticatedSystemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemsRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedSystemsSystemIdRoute =
  AuthenticatedSystemsSystemIdRouteImport.update({
    id: '/$systemId',
    path: '/$systemId',
    getParentRoute: () => AuthenticatedSystemsRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AuthenticatedAccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/systems': typeof AuthenticatedSystemsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/systems/$systemId': typeof AuthenticatedSystemsSystemIdRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/systems/': typeof AuthenticatedSystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AuthenticatedAccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/systems/$systemId': typeof AuthenticatedSystemsSystemIdRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/systems': typeof AuthenticatedSystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRouteWithChildren
  '/_authenticated/systems': typeof AuthenticatedSystemsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/systems/$systemId': typeof AuthenticatedSystemsSystemIdRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/systems/': typeof AuthenticatedSystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/dashboard'
    | '/people'
    | '/systems'
    | '/auth/callback'
    | '/admin/users'
    | '/people/$personId'
    | '/systems/$systemId'
    | '/people/'
    | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access'
    | '/dashboard'
    | '/auth/callback'
    | '/admin/users'
    | '/people/$personId'
    | '/systems/$systemId'
    | '/people'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/access'
    | '/_authenticated/dashboard'
    | '/_authenticated/people'
    | '/_authenticated/systems'
    | '/auth/callback'
    | '/_authenticated/admin/users'
    | '/_authenticated/people/$personId'
    | '/_authenticated/systems/$systemId'
    | '/_authenticated/people/'
    | '/_authenticated/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/systems': {
      id: '/_authenticated/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof AuthenticatedSystemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/systems/': {
      id: '/_authenticated/systems/'
      path: '/'
      fullPath: '/systems/'
      preLoaderRoute: typeof AuthenticatedSystemsIndexRouteImport
      parentRoute: typeof AuthenticatedSystemsRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/systems/$systemId': {
      id: '/_authenticated/systems/$systemId'
      path: '/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof AuthenticatedSystemsSystemIdRouteImport
      parentRoute: typeof AuthenticatedSystemsRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPeopleRouteChildren {
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedPeopleRouteChildren: AuthenticatedPeopleRouteChildren = {
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedPeopleRouteWithChildren =
  AuthenticatedPeopleRoute._addFileChildren(AuthenticatedPeopleRouteChildren)

interface AuthenticatedSystemsRouteChildren {
  AuthenticatedSystemsSystemIdRoute: typeof AuthenticatedSystemsSystemIdRoute
  AuthenticatedSystemsIndexRoute: typeof AuthenticatedSystemsIndexRoute
}

const AuthenticatedSystemsRouteChildren: AuthenticatedSystemsRouteChildren = {
  AuthenticatedSystemsSystemIdRoute: AuthenticatedSystemsSystemIdRoute,
  AuthenticatedSystemsIndexRoute: AuthenticatedSystemsIndexRoute,
}

const AuthenticatedSystemsRouteWithChildren =
  AuthenticatedSystemsRoute._addFileChildren(AuthenticatedSystemsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRouteWithChildren
  AuthenticatedSystemsRoute: typeof AuthenticatedSystemsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRouteWithChildren,
  AuthenticatedSystemsRoute: AuthenticatedSystemsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
