/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated.vendors'
import { Route as AuthenticatedSystemsRouteImport } from './routes/_authenticated.systems'
import { Route as AuthenticatedSlasRouteImport } from './routes/_authenticated.slas'
import { Route as AuthenticatedRisksRouteImport } from './routes/_authenticated.risks'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated.people'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated.access'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated.vendors.index'
import { Route as AuthenticatedSystemsIndexRouteImport } from './routes/_authenticated.systems.index'
import { Route as AuthenticatedSlasIndexRouteImport } from './routes/_authenticated.slas.index'
import { Route as AuthenticatedRisksIndexRouteImport } from './routes/_authenticated.risks.index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated.people.index'
import { Route as AuthenticatedVendorsVendorIdRouteImport } from './routes/_authenticated.vendors.$vendorId'
import { Route as AuthenticatedSystemsSystemIdRouteImport } from './routes/_authenticated.systems.$systemId'
import { Route as AuthenticatedSlasSlaIdRouteImport } from './routes/_authenticated.slas.$slaId'
import { Route as AuthenticatedRisksRiskIdRouteImport } from './routes/_authenticated.risks.$riskId'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated.people.$personId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemsRoute = AuthenticatedSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlasRoute = AuthenticatedSlasRouteImport.update({
  id: '/slas',
  path: '/slas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRisksRoute = AuthenticatedRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorsRoute,
  } as any)
const AuthenticatedSystemsIndexRoute =
  AuthenticatedSystemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemsRoute,
  } as any)
const AuthenticatedSlasIndexRoute = AuthenticatedSlasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlasRoute,
} as any)
const AuthenticatedRisksIndexRoute = AuthenticatedRisksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRisksRoute,
} as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedVendorsVendorIdRoute =
  AuthenticatedVendorsVendorIdRouteImport.update({
    id: '/$vendorId',
    path: '/$vendorId',
    getParentRoute: () => AuthenticatedVendorsRoute,
  } as any)
const AuthenticatedSystemsSystemIdRoute =
  AuthenticatedSystemsSystemIdRouteImport.update({
    id: '/$systemId',
    path: '/$systemId',
    getParentRoute: () => AuthenticatedSystemsRoute,
  } as any)
const AuthenticatedSlasSlaIdRoute = AuthenticatedSlasSlaIdRouteImport.update({
  id: '/$slaId',
  path: '/$slaId',
  getParentRoute: () => AuthenticatedSlasRoute,
} as any)
const AuthenticatedRisksRiskIdRoute =
  AuthenticatedRisksRiskIdRouteImport.update({
    id: '/$riskId',
    path: '/$riskId',
    getParentRoute: () => AuthenticatedRisksRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AuthenticatedAccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/risks': typeof AuthenticatedRisksRouteWithChildren
  '/slas': typeof AuthenticatedSlasRouteWithChildren
  '/systems': typeof AuthenticatedSystemsRouteWithChildren
  '/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/risks/$riskId': typeof AuthenticatedRisksRiskIdRoute
  '/slas/$slaId': typeof AuthenticatedSlasSlaIdRoute
  '/systems/$systemId': typeof AuthenticatedSystemsSystemIdRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/risks/': typeof AuthenticatedRisksIndexRoute
  '/slas/': typeof AuthenticatedSlasIndexRoute
  '/systems/': typeof AuthenticatedSystemsIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AuthenticatedAccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/risks/$riskId': typeof AuthenticatedRisksRiskIdRoute
  '/slas/$slaId': typeof AuthenticatedSlasSlaIdRoute
  '/systems/$systemId': typeof AuthenticatedSystemsSystemIdRoute
  '/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/risks': typeof AuthenticatedRisksIndexRoute
  '/slas': typeof AuthenticatedSlasIndexRoute
  '/systems': typeof AuthenticatedSystemsIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRouteWithChildren
  '/_authenticated/risks': typeof AuthenticatedRisksRouteWithChildren
  '/_authenticated/slas': typeof AuthenticatedSlasRouteWithChildren
  '/_authenticated/systems': typeof AuthenticatedSystemsRouteWithChildren
  '/_authenticated/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/risks/$riskId': typeof AuthenticatedRisksRiskIdRoute
  '/_authenticated/slas/$slaId': typeof AuthenticatedSlasSlaIdRoute
  '/_authenticated/systems/$systemId': typeof AuthenticatedSystemsSystemIdRoute
  '/_authenticated/vendors/$vendorId': typeof AuthenticatedVendorsVendorIdRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/risks/': typeof AuthenticatedRisksIndexRoute
  '/_authenticated/slas/': typeof AuthenticatedSlasIndexRoute
  '/_authenticated/systems/': typeof AuthenticatedSystemsIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/dashboard'
    | '/people'
    | '/risks'
    | '/slas'
    | '/systems'
    | '/vendors'
    | '/auth/callback'
    | '/admin/users'
    | '/people/$personId'
    | '/risks/$riskId'
    | '/slas/$slaId'
    | '/systems/$systemId'
    | '/vendors/$vendorId'
    | '/people/'
    | '/risks/'
    | '/slas/'
    | '/systems/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access'
    | '/dashboard'
    | '/auth/callback'
    | '/admin/users'
    | '/people/$personId'
    | '/risks/$riskId'
    | '/slas/$slaId'
    | '/systems/$systemId'
    | '/vendors/$vendorId'
    | '/people'
    | '/risks'
    | '/slas'
    | '/systems'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/access'
    | '/_authenticated/dashboard'
    | '/_authenticated/people'
    | '/_authenticated/risks'
    | '/_authenticated/slas'
    | '/_authenticated/systems'
    | '/_authenticated/vendors'
    | '/auth/callback'
    | '/_authenticated/admin/users'
    | '/_authenticated/people/$personId'
    | '/_authenticated/risks/$riskId'
    | '/_authenticated/slas/$slaId'
    | '/_authenticated/systems/$systemId'
    | '/_authenticated/vendors/$vendorId'
    | '/_authenticated/people/'
    | '/_authenticated/risks/'
    | '/_authenticated/slas/'
    | '/_authenticated/systems/'
    | '/_authenticated/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/systems': {
      id: '/_authenticated/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof AuthenticatedSystemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/slas': {
      id: '/_authenticated/slas'
      path: '/slas'
      fullPath: '/slas'
      preLoaderRoute: typeof AuthenticatedSlasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risks': {
      id: '/_authenticated/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof AuthenticatedRisksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedVendorsRoute
    }
    '/_authenticated/systems/': {
      id: '/_authenticated/systems/'
      path: '/'
      fullPath: '/systems/'
      preLoaderRoute: typeof AuthenticatedSystemsIndexRouteImport
      parentRoute: typeof AuthenticatedSystemsRoute
    }
    '/_authenticated/slas/': {
      id: '/_authenticated/slas/'
      path: '/'
      fullPath: '/slas/'
      preLoaderRoute: typeof AuthenticatedSlasIndexRouteImport
      parentRoute: typeof AuthenticatedSlasRoute
    }
    '/_authenticated/risks/': {
      id: '/_authenticated/risks/'
      path: '/'
      fullPath: '/risks/'
      preLoaderRoute: typeof AuthenticatedRisksIndexRouteImport
      parentRoute: typeof AuthenticatedRisksRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/vendors/$vendorId': {
      id: '/_authenticated/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AuthenticatedVendorsVendorIdRouteImport
      parentRoute: typeof AuthenticatedVendorsRoute
    }
    '/_authenticated/systems/$systemId': {
      id: '/_authenticated/systems/$systemId'
      path: '/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof AuthenticatedSystemsSystemIdRouteImport
      parentRoute: typeof AuthenticatedSystemsRoute
    }
    '/_authenticated/slas/$slaId': {
      id: '/_authenticated/slas/$slaId'
      path: '/$slaId'
      fullPath: '/slas/$slaId'
      preLoaderRoute: typeof AuthenticatedSlasSlaIdRouteImport
      parentRoute: typeof AuthenticatedSlasRoute
    }
    '/_authenticated/risks/$riskId': {
      id: '/_authenticated/risks/$riskId'
      path: '/$riskId'
      fullPath: '/risks/$riskId'
      preLoaderRoute: typeof AuthenticatedRisksRiskIdRouteImport
      parentRoute: typeof AuthenticatedRisksRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPeopleRouteChildren {
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedPeopleRouteChildren: AuthenticatedPeopleRouteChildren = {
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedPeopleRouteWithChildren =
  AuthenticatedPeopleRoute._addFileChildren(AuthenticatedPeopleRouteChildren)

interface AuthenticatedRisksRouteChildren {
  AuthenticatedRisksRiskIdRoute: typeof AuthenticatedRisksRiskIdRoute
  AuthenticatedRisksIndexRoute: typeof AuthenticatedRisksIndexRoute
}

const AuthenticatedRisksRouteChildren: AuthenticatedRisksRouteChildren = {
  AuthenticatedRisksRiskIdRoute: AuthenticatedRisksRiskIdRoute,
  AuthenticatedRisksIndexRoute: AuthenticatedRisksIndexRoute,
}

const AuthenticatedRisksRouteWithChildren =
  AuthenticatedRisksRoute._addFileChildren(AuthenticatedRisksRouteChildren)

interface AuthenticatedSlasRouteChildren {
  AuthenticatedSlasSlaIdRoute: typeof AuthenticatedSlasSlaIdRoute
  AuthenticatedSlasIndexRoute: typeof AuthenticatedSlasIndexRoute
}

const AuthenticatedSlasRouteChildren: AuthenticatedSlasRouteChildren = {
  AuthenticatedSlasSlaIdRoute: AuthenticatedSlasSlaIdRoute,
  AuthenticatedSlasIndexRoute: AuthenticatedSlasIndexRoute,
}

const AuthenticatedSlasRouteWithChildren =
  AuthenticatedSlasRoute._addFileChildren(AuthenticatedSlasRouteChildren)

interface AuthenticatedSystemsRouteChildren {
  AuthenticatedSystemsSystemIdRoute: typeof AuthenticatedSystemsSystemIdRoute
  AuthenticatedSystemsIndexRoute: typeof AuthenticatedSystemsIndexRoute
}

const AuthenticatedSystemsRouteChildren: AuthenticatedSystemsRouteChildren = {
  AuthenticatedSystemsSystemIdRoute: AuthenticatedSystemsSystemIdRoute,
  AuthenticatedSystemsIndexRoute: AuthenticatedSystemsIndexRoute,
}

const AuthenticatedSystemsRouteWithChildren =
  AuthenticatedSystemsRoute._addFileChildren(AuthenticatedSystemsRouteChildren)

interface AuthenticatedVendorsRouteChildren {
  AuthenticatedVendorsVendorIdRoute: typeof AuthenticatedVendorsVendorIdRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
}

const AuthenticatedVendorsRouteChildren: AuthenticatedVendorsRouteChildren = {
  AuthenticatedVendorsVendorIdRoute: AuthenticatedVendorsVendorIdRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
}

const AuthenticatedVendorsRouteWithChildren =
  AuthenticatedVendorsRoute._addFileChildren(AuthenticatedVendorsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRouteWithChildren
  AuthenticatedRisksRoute: typeof AuthenticatedRisksRouteWithChildren
  AuthenticatedSlasRoute: typeof AuthenticatedSlasRouteWithChildren
  AuthenticatedSystemsRoute: typeof AuthenticatedSystemsRouteWithChildren
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRouteWithChildren,
  AuthenticatedRisksRoute: AuthenticatedRisksRouteWithChildren,
  AuthenticatedSlasRoute: AuthenticatedSlasRouteWithChildren,
  AuthenticatedSystemsRoute: AuthenticatedSystemsRouteWithChildren,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
